// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS2FwlcNyU_SfK769syuVUpWMAvu7AXHE',
    appId: '1:138056387893:web:b8239eb74a3d5d4334107c',
    messagingSenderId: '138056387893',
    projectId: 'miniwheelscars',
    authDomain: 'miniwheelscars.firebaseapp.com',
    storageBucket: 'miniwheelscars.firebasestorage.app',
    measurementId: 'G-97Q5X9WWTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAriKqQtgB5RdpIpPtHeFbUzw4hSENhIc',
    appId: '1:138056387893:android:8f76ed242657445134107c',
    messagingSenderId: '138056387893',
    projectId: 'miniwheelscars',
    storageBucket: 'miniwheelscars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Q6_-2gZBUMjmXhs1xkstwO87oot62HM',
    appId: '1:138056387893:ios:526e8b164d8e88e434107c',
    messagingSenderId: '138056387893',
    projectId: 'miniwheelscars',
    storageBucket: 'miniwheelscars.firebasestorage.app',
    iosBundleId: 'com.example.miniWheelzUser',
  );
}
